name: DVF Pipeline

on:
  schedule:
    - cron: "0 6 * * 1"  # chaque lundi à 6h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ingestion script
        run: python src/ingestion/download_dvf.py

      - name: Run cleaning script
        run: python src/cleaning/clean_dvf.py

      - name: Commit and push CSV
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/dvf_clean.csv
          git commit -m "Mise à jour automatique des données DVF" || echo "Aucun changement à committer"
          git push
